KEYS=['title','intro','start','continue','done','personal','fallback','goal','goal_mate','white','black','select','hint','reveal','next','retry','legal','correct','shown','hint_text','connection','finish','independent','helped','summary','back','analyze','source','day','sessions','promotion','queen','rook','bishop','knight','opening','middlegame','endgame','general','mate_fact','check_fact','capture_fact','castle_fact','move_fact','solution','review_help','previous','no_repeat','choose_move']
ROWS={
'es':['Entrenamiento de hoy','Tres posiciones, unos cinco minutos. Mirá el tablero y elegí una jugada antes de pedir ayuda.','Empezar mi entrenamiento','Continuar entrenamiento','Entrenamiento completado','De tus partidas analizadas','Práctica de mate. Al analizar tus partidas podremos usar tus propias posiciones.','Buscá una mejor jugada que la que elegiste en la partida.','Encontrá un mate en una jugada.','Juegan blancas','Juegan negras','Tocá una pieza y después la casilla de destino.','Pedir una pista','Ver la solución','Siguiente posición','Probá otra jugada.','La jugada es legal, pero el motor recomendó otra. Buscá una alternativa.','¡Bien! Encontraste la jugada recomendada.','Solución vista. Podés volver a practicar esta posición otro día.','Mirá las jugadas de esta pieza: {piece}.','No pudimos guardar la jugada. Intentá de nuevo; tu avance anterior sigue guardado.','Listo por hoy','Resueltas al primer intento, sin pistas','Con pistas, solución o más intentos','Completaste {total} posiciones. No hay límite de tiempo: lo importante es entenderlas.','Volver a Entrenar','Analizar una partida','Ver la partida analizada','Día','Entrenamientos completados en los últimos siete días','Elegí la pieza para coronar','Dama','Torre','Alfil','Caballo','Apertura','Medio juego','Final','Práctica','Esta jugada da jaque mate: el rey no tiene ninguna respuesta legal.','Esta jugada da jaque. El rival tiene que responder a la amenaza sobre su rey.','Esta jugada captura una pieza rival.','Esta jugada enroca al rey y activa la torre.','Probá reconocer esta opción cuando vuelva a aparecer una posición parecida.','Jugada recomendada: {move}.','Para personalizar más tu práctica, analizá una partida al terminar de jugar.','Último entrenamiento','Hoy repetimos algunas posiciones para afianzar lo aprendido.','Elegí tu jugada'],
'pt':['Treino de hoje','Três posições, cerca de cinco minutos. Observe o tabuleiro e escolha uma jogada antes de pedir ajuda.','Começar meu treino','Continuar treino','Treino concluído','Das suas partidas analisadas','Prática de mate. Ao analisar suas partidas, poderemos usar suas próprias posições.','Encontre uma jogada melhor que a escolhida na partida.','Encontre um mate em uma jogada.','Brancas jogam','Pretas jogam','Toque em uma peça e depois na casa de destino.','Pedir uma dica','Ver a solução','Próxima posição','Tente outra jogada.','A jogada é legal, mas o motor recomendou outra. Procure uma alternativa.','Muito bem! Você encontrou a jogada recomendada.','Solução vista. Você pode praticar esta posição novamente outro dia.','Observe as jogadas desta peça: {piece}.','Não conseguimos salvar a jogada. Tente novamente; seu progresso anterior está salvo.','Concluído por hoje','Resolvidas na primeira tentativa, sem dicas','Com dicas, solução ou mais tentativas','Você completou {total} posições. Não há limite de tempo: o importante é entendê-las.','Voltar a Treinar','Analisar uma partida','Ver a partida analisada','Dia','Treinos concluídos nos últimos sete dias','Escolha a peça para promover','Dama','Torre','Bispo','Cavalo','Abertura','Meio-jogo','Final','Prática','Esta jogada dá xeque-mate: o rei não tem nenhuma resposta legal.','Esta jogada dá xeque. O adversário precisa responder à ameaça ao rei.','Esta jogada captura uma peça adversária.','Esta jogada faz o roque e ativa a torre.','Tente reconhecer esta opção quando surgir uma posição parecida.','Jogada recomendada: {move}.','Para personalizar sua prática, analise uma partida depois de jogar.','Último treino','Hoje repetimos algumas posições para reforçar o aprendizado.','Escolha sua jogada'],
'en':['Today’s training','Three positions, about five minutes. Look at the board and choose a move before asking for help.','Start my training','Continue training','Training completed','From your analyzed games','Mate practice. Analyze your games so we can use your own positions.','Find a better move than the one you played.','Find checkmate in one move.','White to move','Black to move','Tap a piece, then its destination square.','Get a hint','Show solution','Next position','Try another move.','That move is legal, but the engine recommended another. Look for an alternative.','Well done! You found the recommended move.','Solution viewed. You can practice this position again another day.','Look at moves by this piece: {piece}.','We could not save the move. Try again; your earlier progress is saved.','Done for today','Solved on the first try, without hints','With hints, solutions or more attempts','You completed {total} positions. There is no time limit: understanding matters most.','Back to Training','Analyze a game','View analyzed game','Day','Training sessions completed in the last seven days','Choose a promotion piece','Queen','Rook','Bishop','Knight','Opening','Middlegame','Endgame','Practice','This move is checkmate: the king has no legal response.','This move gives check. Your opponent must answer the threat to their king.','This move captures an opposing piece.','This move castles the king and activates the rook.','Try to recognize this option when a similar position comes up.','Recommended move: {move}.','Analyze a game after playing to personalize your practice.','Last training session','Today includes a few repeated positions to reinforce learning.','Choose your move'],
}
TEXTS={lang:dict(zip(KEYS,row)) for lang,row in ROWS.items()}
def daily_training_navigation(request):
 from .i18n import current_language
 return {'dt':TEXTS[current_language(request)]}

for lang,names in {'es':['peón','caballo','alfil','torre','dama','rey'],'pt':['peão','cavalo','bispo','torre','dama','rei'],'en':['pawn','knight','bishop','rook','queen','king']}.items():
 TEXTS[lang]['piece_names']=dict(zip('pnbrqk',names))
