KEYS=('intro','coach','coach_help','friends','friends_help','friends_action','train','train_help','train_action','setup','level','level_help','easy','casual','regular','club','advanced','expert','master','start_help','resume','board_help','coach_help_title','coach_help_text','review_first','review_help','practice_review','practice_help','practice_title','practice_intro','no_positions','back_review','practice_finish','practice_summary','practice_first','practice_helped','practice_again','see_progress')
ROWS={
'es':('Elegí por dónde empezar. Jugá una partida, entendé tus jugadas y volvé para seguir mejorando.','Jugar con el coach','Jugá a tu ritmo y preguntale al coach qué plan seguir o por qué una jugada conviene.','Jugar con amigos','Invitá a alguien con un enlace o elegí un amigo de tu cuenta.','Invitar a jugar','Entrenar','Resolvé posiciones cortas sin reloj y después probá el desafío semanal.','Empezar a entrenar','Prepará tu partida','Nivel del coach','Si recién empezás, elegí Principiante. Podés probar un nivel más difícil en la próxima partida.','Principiante · 500','Tranquilo · 800','Intermedio · 1000','Club · 1320','Avanzado · 1600','Experto · 2000','Máximo · 2500','Esta partida no tiene reloj. Tocá una pieza y después la casilla a la que querés moverla.','Retomar mi partida','Elegí una pieza y después su destino. Podés volver atrás para revisar una jugada.','¿Cómo me ayuda el coach?','Escribile una pregunta sobre la posición o usá las preguntas sugeridas. Activá los comentarios si querés una explicación después de tus jugadas. Podés jugar sin activar ninguna ayuda.','Primero, entendé tu partida','Revisá las jugadas antes de empezar otra partida. Después podés practicar los errores y ver tu progreso.','Practicar errores de esta partida','Volvé a las posiciones de tus errores y probá una alternativa. Esta práctica no cambia tu Elo ni suma puntos.','Repasá esta partida','Probá una alternativa en las posiciones que dejó tu análisis. Podés pedir pistas y repetir sin reloj.','Esta revisión no tiene errores con una alternativa verificada para practicar. Podés leer el resumen o ir a práctica guiada.','Volver a la revisión','Repaso completado','Practicaste {total} posiciones de esta partida. Volvé a tu revisión para elegir una idea para el próximo juego.','Resueltas al primer intento','Resueltas con ayuda o reintentos','Repetir el repaso','Ver mi aprendizaje'),
'pt':('Escolha por onde começar. Jogue uma partida, entenda suas jogadas e volte para continuar melhorando.','Jogar com o coach','Jogue no seu ritmo e pergunte ao coach qual plano seguir ou por que uma jogada é boa.','Jogar com amigos','Convide alguém por um link ou escolha um amigo da sua conta.','Convidar para jogar','Treinar','Resolva posições curtas sem relógio e depois experimente o desafio semanal.','Começar a treinar','Prepare sua partida','Nível do coach','Se está começando, escolha Iniciante. Experimente um nível mais difícil na próxima partida.','Iniciante · 500','Tranquilo · 800','Intermediário · 1000','Clube · 1320','Avançado · 1600','Especialista · 2000','Máximo · 2500','Esta partida não tem relógio. Toque numa peça e depois na casa de destino.','Retomar minha partida','Escolha uma peça e depois seu destino. Volte atrás para revisar uma jogada.','Como o coach me ajuda?','Escreva uma pergunta sobre a posição ou use as perguntas sugeridas. Ative comentários se quiser explicações após suas jogadas. Você pode jogar sem ativar nenhuma ajuda.','Primeiro, entenda sua partida','Revise as jogadas antes de começar outra partida. Depois pratique os erros e veja seu progresso.','Praticar erros desta partida','Volte às posições dos seus erros e tente uma alternativa. Esta prática não altera Elo ou pontos.','Revise esta partida','Experimente uma alternativa nas posições da sua análise. Peça dicas e repita sem relógio.','Esta revisão não tem erros com uma alternativa verificada para praticar. Leia o resumo ou vá à prática guiada.','Voltar à revisão','Revisão concluída','Você praticou {total} posições desta partida. Volte à revisão e escolha uma ideia para o próximo jogo.','Resolvidas na primeira tentativa','Resolvidas com ajuda ou repetições','Repetir a prática','Ver meu aprendizado'),
'en':('Choose where to start. Play a game, understand your moves and come back to keep improving.','Play with the coach','Play at your own pace and ask the coach what plan to follow or why a move helps.','Play with friends','Invite someone with a link or choose a friend from your account.','Invite a player','Train','Solve short positions without a clock, then try the weekly challenge.','Start training','Set up your game','Coach level','If you are new, choose Beginner. Try a harder level in your next game.','Beginner · 500','Relaxed · 800','Intermediate · 1000','Club · 1320','Advanced · 1600','Expert · 2000','Maximum · 2500','This game has no clock. Select a piece, then its destination square.','Resume my game','Select a piece, then its destination. Go back to review a move.','How does the coach help?','Ask about the position or use the suggested questions. Enable comments if you want explanations after your moves. You can play without enabling any help.','First, understand your game','Review your moves before another game. Then practice mistakes and see your progress.','Practice mistakes from this game','Revisit your mistakes and try an alternative. This practice does not change Elo or award points.','Revisit this game','Try an alternative in positions from your analysis. Ask for hints and repeat without a clock.','This review has no mistakes with a verified alternative to practice. Read the summary or open guided practice.','Back to review','Practice completed','You practiced {total} positions from this game. Return to the review and choose an idea for your next game.','Solved on the first attempt','Solved with hints or retries','Repeat practice','View my learning'),
}
TEXTS={lang:dict(zip(KEYS,row)) for lang,row in ROWS.items()}
def first_steps_context(request):
    from .i18n import current_language
    return {'flow':TEXTS[current_language(request)]}

for lang,notice in {
 'es':' Al completar el repaso, el objetivo de esta revisión queda marcado en Mi aprendizaje.',
 'pt':' Ao concluir a prática, a meta desta revisão fica marcada em Meu aprendizado.',
 'en':' Completing practice marks this review’s goal in My learning.',
}.items():
    TEXTS[lang]['practice_help']+=notice

TEXTS['es']['practice_summary']='Posiciones practicadas: {total}. Volvé a tu revisión para elegir una idea para la próxima partida.'
TEXTS['pt']['practice_summary']='Posições praticadas: {total}. Volte à revisão e escolha uma ideia para a próxima partida.'
TEXTS['en']['practice_summary']='Positions practiced: {total}. Return to the review and choose an idea for your next game.'
