KEYS=('title','intro','habit','habit_help','goal','goal_done','days','completed','in_progress','not_started','today','daily','daily_help','weekly','weekly_help','first','first_help','positions','recent_activity','activity_empty','review','open','continue','start_daily','continue_daily','daily_next','daily_resume','weekly_next','continue_weekly','review_next','review_action','practice_next','practice_action','week','points','attempts','advanced','calendar','day_done','day_started','day_empty','current','history','goal_reached')
ROWS={
'es':('Tu progreso, de un vistazo','Entrená, repasá tus partidas y elegí tu próximo paso.','Tu hábito de entrenamiento','Contamos planes diarios completados en los últimos 7 días. Las pistas también sirven para aprender.','Una meta simple: entrenar 3 días','Meta alcanzada','días de entrenamiento','Completado','En curso','Sin empezar','Hoy','Entrenamiento de hoy','Tres posiciones para practicar. Si tenés errores analizados, usamos esos momentos de tus partidas.','Desafío semanal','Las mismas cinco posiciones para vos y tus amigos. Podés seguir practicando después de puntuar.','Aciertos al primer intento','De los ejercicios diarios resueltos en los últimos 7 días, sin pistas ni reintentos. No representa tu Elo ni tu fuerza de juego.','ejercicios resueltos','Tu actividad reciente','Tu actividad aparecerá cuando entrenes o guardes una revisión.','Revisión de partida','Abrir','Continuar','Empezar entrenamiento','Retomar entrenamiento','Empezá con las tres posiciones de hoy. Practicá sin reloj y pedí una pista si la necesitás.','Tu entrenamiento de hoy quedó empezado. Retomalo desde la posición que dejaste.','Ya completaste el entrenamiento de hoy. Probá ahora el desafío semanal y compará tu resultado con tus amigos.','Ir al desafío semanal','Repasá los momentos destacados de tu última revisión pendiente y elegí una idea para la próxima partida.','Repasar mi partida','Ya completaste los desafíos actuales. Podés practicar sin reloj o volver a los errores de tus partidas.','Ir a práctica guiada','Semana','puntos','intentos puntuados','Detalles del análisis de partidas','Últimos 7 días','Plan completado','Plan en curso','Sin plan completado','Tu próximo paso','Ver historial de desafíos','Completaste la meta. Podés seguir a tu ritmo.'),
'pt':('Seu progresso em um olhar','Treine, revise suas partidas e escolha o próximo passo.','Seu hábito de treino','Contamos planos diários concluídos nos últimos 7 dias. Dicas também ajudam a aprender.','Uma meta simples: treinar 3 dias','Meta alcançada','dias de treino','Concluído','Em andamento','Não iniciado','Hoje','Treino de hoje','Três posições para praticar. Se houver erros analisados, usamos esses momentos das suas partidas.','Desafio semanal','As mesmas cinco posições para você e seus amigos. Você pode continuar praticando depois de pontuar.','Acertos na primeira tentativa','Dos exercícios diários resolvidos nos últimos 7 dias, sem dicas nem repetições. Não representa seu Elo ou força de jogo.','exercícios resolvidos','Sua atividade recente','Sua atividade aparecerá quando treinar ou salvar uma revisão.','Revisão de partida','Abrir','Continuar','Começar treino','Retomar treino','Comece com as três posições de hoje. Pratique sem relógio e peça uma dica se precisar.','Seu treino de hoje foi iniciado. Retome da posição em que parou.','Você concluiu o treino de hoje. Experimente o desafio semanal e compare seu resultado com seus amigos.','Ir ao desafio semanal','Revise os momentos destacados da sua última revisão pendente e escolha uma ideia para a próxima partida.','Revisar minha partida','Você concluiu os desafios atuais. Pratique sem relógio ou volte aos erros das suas partidas.','Ir à prática guiada','Semana','pontos','tentativas pontuadas','Detalhes da análise de partidas','Últimos 7 dias','Plano concluído','Plano em andamento','Sem plano concluído','Seu próximo passo','Ver histórico de desafios','Você atingiu a meta. Continue no seu ritmo.'),
'en':('Your progress at a glance','Train, review your games and choose your next step.','Your training habit','We count daily plans completed in the last 7 days. Hints help you learn too.','A simple goal: train on 3 days','Goal reached','training days','Completed','In progress','Not started','Today',"Today's training",'Three positions to practice. If you have analyzed mistakes, we use those moments from your games.','Weekly challenge','The same five positions for you and your friends. Keep practicing after scoring.','First-attempt successes','Of daily exercises solved in the last 7 days, without hints or retries. This does not represent your Elo or playing strength.','exercises solved','Your recent activity','Activity will appear when you train or save a review.','Game review','Open','Continue','Start training','Resume training',"Start with today's three positions. Practice without a clock and ask for a hint if you need one.","Today's training is in progress. Resume from where you left off.","You completed today's training. Try the weekly challenge and compare your result with your friends.",'Open weekly challenge','Revisit the highlighted moments in your latest pending review and choose one idea for your next game.','Review my game','You completed the current challenges. Practice without a clock or revisit mistakes from your games.','Open guided practice','Week','points','scored attempts','Game analysis details','Last 7 days','Plan completed','Plan in progress','No completed plan','Your next step','View challenge history','You reached the goal. Keep going at your own pace.'),
}
TEXTS={lang:dict(zip(KEYS,row)) for lang,row in ROWS.items()}

for lang,values in {
 'es':['Entrenamiento diario','Qué conviene repasar','Todavía no resolviste ejercicios en estos 7 días.','día de entrenamiento'],
 'pt':['Treino diário','O que vale revisar','Você ainda não resolveu exercícios nestes 7 dias.','dia de treino'],
 'en':['Daily training','What to revisit','You have not solved exercises in these 7 days yet.','training day'],
}.items():
    TEXTS[lang].update(zip(['daily_activity','focus_title','no_exercises','day'],values))
