KEYS = ('title','intro','search','search_hint','find','add','accept','decline','cancel','remove','friends','incoming','outgoing','empty','online','offline','challenge','challenge_help','casual','ranked','minutes','ranking','ranking_help','puzzles','elo','blitz','streak','you','wins','losses','draws','history','no_results','pending','accepted','updated','sent','privacy','no_record','refresh')
ROWS = {
 'es': ('Amigos','Aprendan juntos, compitan y jueguen la revancha.','Buscar jugadores','Nombre de usuario · mínimo 2 caracteres','Buscar','Agregar amigo','Aceptar','Rechazar','Cancelar solicitud','Eliminar amistad','Tus amigos','Solicitudes recibidas','Solicitudes enviadas','Todavía no tenés amigos. Buscá a un conocido por su nombre de usuario.','Conectado','Sin conexión reciente','Desafiar','La invitación llega dentro de Gchess. El reloj comienza al jugar; no mientras esperan.','Casual · sin cambiar Elo','Competitiva · cambia Elo','Minutos por jugador','Ranking entre amigos','Incluye tus amigos y tu cuenta. Cada clasificación usa una medida distinta. — significa que todavía no hay un registro.','Rating de puzzles','Elo de partidas','Blitz · puntos','Racha · puzzles','Vos','Victorias','Derrotas','Tablas','Tus resultados contra este amigo','No encontramos jugadores con ese nombre.','Solicitud pendiente','Ya son amigos','Cambios guardados.','Solicitud enviada. La otra persona tiene que aceptarla.','Solo se muestran nombres de usuario y estadísticas de juego, nunca correos.','Sin registro','Actualizar'),
 'pt': ('Amigos','Aprendam juntos, compitam e joguem a revanche.','Buscar jogadores','Nome de usuário · mínimo 2 caracteres','Buscar','Adicionar amigo','Aceitar','Recusar','Cancelar solicitação','Remover amizade','Seus amigos','Solicitações recebidas','Solicitações enviadas','Você ainda não tem amigos. Busque alguém pelo nome de usuário.','Online','Sem conexão recente','Desafiar','O convite chega dentro do Gchess. O relógio começa ao jogar, não durante a espera.','Casual · sem alterar Elo','Competitiva · altera Elo','Minutos por jogador','Ranking entre amigos','Inclui seus amigos e sua conta. Cada classificação usa uma medida diferente. — indica que ainda não há registro.','Rating de puzzles','Elo de partidas','Blitz · pontos','Sequência · puzzles','Você','Vitórias','Derrotas','Empates','Seus resultados contra este amigo','Nenhum jogador encontrado.','Solicitação pendente','Vocês já são amigos','Alterações salvas.','Solicitação enviada. A outra pessoa precisa aceitá-la.','Mostramos apenas nomes de usuário e estatísticas de jogo, nunca e-mails.','Sem registro','Atualizar'),
 'en': ('Friends','Learn together, compete and play a rematch.','Find players','Username · at least 2 characters','Search','Add friend','Accept','Decline','Cancel request','Remove friendship','Your friends','Incoming requests','Sent requests','No friends yet. Find someone by username.','Online','Not recently online','Challenge','Invitations arrive inside Gchess. The clock starts when playing, not while waiting.','Casual · no Elo change','Rated · changes Elo','Minutes per player','Friends leaderboard','Includes your friends and your account. Each board uses a separate measure. — means there is no record yet.','Puzzle rating','Game Elo','Blitz · points','Streak · puzzles','You','Wins','Losses','Draws','Your results against this friend','No players found.','Request pending','Already friends','Changes saved.','Request sent. The other person must accept it.','Only usernames and game statistics are shown, never email addresses.','No record','Refresh'),
}
SOCIAL_TEXTS = {lang: dict(zip(KEYS, row, strict=True)) for lang, row in ROWS.items()}


def social_navigation(request):
    from .i18n import current_language
    from .models import Friendship
    count = 0
    if request.user.is_authenticated:
        from django.db.models import Q
        count = Friendship.objects.filter(Q(low_user=request.user) | Q(high_user=request.user), status='pending').exclude(requester=request.user).count()
    return {'social_nav_title': SOCIAL_TEXTS[current_language(request)]['title'], 'friend_request_count': count}
