KEYS = ['nav','intro','create','mine','name','capacity','minutes','rules','lobby','active','finished','cancelled','join','leave','start','cancel','share','copy','copied','players','host','round','play','waiting','standings','points','wins','draws','losses','bye','rounds','empty','full','closed','min_players','owner_only','join_first','results','white','black','pending','unknown','cancel_confirm','create_help','share_help','round_help','clock_help','tie_help','login_help','view','no_game','ready']
ROWS = {
'es': ['Torneos','Creá un torneo privado, compartí el enlace y competí con tus amigos.','Crear torneo','Mis torneos','Nombre del torneo','Máximo de jugadores','Minutos por jugador','Todos contra todos. Una partida por rival. Victoria: 1 punto; empate: ½; derrota: 0. Con jugadores impares, cada uno tiene un descanso de 1 punto. Las partidas no cambian el Elo.','Inscripción abierta','En juego','Finalizado','Cancelado','Unirme','Salir del torneo','Iniciar torneo','Cancelar torneo','Enlace para invitar','Copiar enlace','Enlace copiado','Jugadores','Organizador','Ronda','Jugar mi partida','Esperando que termine la ronda','Posiciones','Puntos','Victorias','Empates','Derrotas','Descanso · 1 punto','Rondas y partidas','Todavía no tenés torneos. Creá uno o abrí el enlace de un amigo.','El torneo está completo.','La inscripción ya está cerrada.','Necesitás al menos dos jugadores para empezar.','Solo el organizador puede hacer esto.','Unite al torneo para jugar.','Resultados','Blancas','Negras','Por jugar','Resultado pendiente de confirmar','¿Cancelar este torneo?','Elegí el tiempo y compartí el enlace. Cuando estén tus amigos, iniciá el torneo.','Quien tenga este enlace y una cuenta puede unirse mientras haya lugar.','La siguiente ronda se abre cuando terminan todas las partidas de la actual.','El reloj comienza con la primera jugada. Al cambiar de página, sigue corriendo.','Con los mismos puntos, los jugadores comparten posición. No se usan desempates en esta primera versión.','Necesitás una cuenta para participar.','Ver torneo','Tu partida aparecerá cuando se abra la próxima ronda.','Tu partida está lista'],
'pt': ['Torneios','Crie um torneio privado, compartilhe o link e jogue com seus amigos.','Criar torneio','Meus torneios','Nome do torneio','Máximo de jogadores','Minutos por jogador','Todos contra todos. Uma partida por adversário. Vitória: 1 ponto; empate: ½; derrota: 0. Com jogadores ímpares, cada um recebe um descanso de 1 ponto. As partidas não mudam o Elo.','Inscrições abertas','Em jogo','Finalizado','Cancelado','Participar','Sair do torneio','Iniciar torneio','Cancelar torneio','Link para convidar','Copiar link','Link copiado','Jogadores','Organizador','Rodada','Jogar minha partida','Esperando o fim da rodada','Classificação','Pontos','Vitórias','Empates','Derrotas','Descanso · 1 ponto','Rodadas e partidas','Você ainda não tem torneios. Crie um ou abra o link de um amigo.','O torneio está cheio.','As inscrições estão encerradas.','São necessários pelo menos dois jogadores.','Só o organizador pode fazer isso.','Entre no torneio para jogar.','Resultados','Brancas','Pretas','A jogar','Resultado aguardando confirmação','Cancelar este torneio?','Escolha o tempo e compartilhe o link. Quando seus amigos estiverem prontos, inicie o torneio.','Quem tiver este link e uma conta pode entrar enquanto houver vagas.','A próxima rodada começa quando todas as partidas da atual terminam.','O relógio começa na primeira jogada. Continua correndo ao mudar de página.','Com os mesmos pontos, os jogadores dividem a posição. Esta versão não usa desempates.','Você precisa de uma conta para participar.','Ver torneio','Sua partida aparece quando a próxima rodada começar.','Sua partida está pronta'],
'en': ['Tournaments','Create a private tournament, share the link and compete with friends.','Create tournament','My tournaments','Tournament name','Maximum players','Minutes per player','Round robin. One game per opponent. Win: 1 point; draw: ½; loss: 0. With an odd number of players, each receives a one-point bye. Games do not change Elo.','Registration open','Playing','Finished','Cancelled','Join','Leave tournament','Start tournament','Cancel tournament','Invitation link','Copy link','Link copied','Players','Host','Round','Play my game','Waiting for the round to finish','Standings','Points','Wins','Draws','Losses','Bye · 1 point','Rounds and games','No tournaments yet. Create one or open a friend’s link.','The tournament is full.','Registration is closed.','At least two players are needed to start.','Only the host can do this.','Join the tournament to play.','Results','White','Black','Not started','Result awaiting confirmation','Cancel this tournament?','Choose the time and share the link. Start when your friends are ready.','Anyone with this link and an account can join while places remain.','The next round opens when all games in the current round finish.','The clock starts with the first move and keeps running when you switch pages.','Players with equal points share a place. This version has no tiebreaks.','An account is required to participate.','View tournament','Your game appears when the next round opens.','Your game is ready'],
}
TEXTS = {language: dict(zip(KEYS, row)) for language, row in ROWS.items()}

def tournament_navigation(request):
    from .i18n import current_language
    return {'tournament_texts': TEXTS[current_language(request)]}

for language,labels in {
    'es': ('Cómo se juega', 'Primer puesto'),
    'pt': ('Como jogar', 'Primeiro lugar'),
    'en': ('How it works', 'First place'),
}.items():
    TEXTS[language]['rules_title'], TEXTS[language]['first_place'] = labels

for language,values in {
 'es': ['Invitar amigos','Invitar','Invitación enviada','Todavía no tenés amigos disponibles para invitar. Podés compartir el enlace.','Te invitaron a {name}. Abrí el torneo para unirte.','{name}: la ronda {round} está lista. Revisá tu partida o descanso.','Ocultar','Avisos','No hay avisos pendientes.'],
 'pt': ['Convidar amigos','Convidar','Convite enviado','Nenhum amigo disponível para convidar. Você pode compartilhar o link.','Você recebeu um convite para {name}. Abra o torneio para participar.','{name}: a rodada {round} está pronta. Confira sua partida ou descanso.','Dispensar','Avisos','Nenhum aviso pendente.'],
 'en': ['Invite friends','Invite','Invitation sent','No friends available to invite. You can share the link.','You are invited to {name}. Open the tournament to join.','{name}: round {round} is ready. Check your game or bye.','Dismiss','Notifications','No pending notifications.'],
}.items():
 TEXTS[language].update(zip(['invite_friends','invite','sent','no_friends','invite_notice','round_notice','dismiss','notifications','no_notifications'],values))

for language,values in {
'es':['Público','Privado','Visibilidad','Contraseña del torneo','Público: aparece en Torneos. Privado: solo por enlace o invitación y con contraseña.','Usá entre 6 y 128 caracteres. Compartila con quienes quieras invitar; no uses la contraseña de tu cuenta.','El torneo privado necesita una contraseña de al menos 6 caracteres.','La contraseña no es correcta o todavía no fue configurada.','Torneo privado','Ingresá la contraseña para unirte. Los invitados también la necesitan.','Guardar contraseña','Contraseña guardada. Los jugadores inscritos conservan su acceso.','Configurar contraseña','Este torneo fue creado antes de esta opción. Configurá una contraseña para permitir nuevas inscripciones.','Compartí el enlace y la contraseña por separado con tus invitados.','Torneos públicos','Descubrí una copa y unite mientras la inscripción esté abierta.','No hay torneos públicos en este estado. Podés crear uno.','Cupos','Inicio manual por el organizador','Ver posiciones','Página','Anterior','Siguiente','Inscripción abierta','En juego','Finalizados'],
'pt':['Público','Privado','Visibilidade','Senha do torneio','Público: aparece em Torneios. Privado: apenas por link ou convite, com senha.','Use de 6 a 128 caracteres. Compartilhe com seus convidados; não use a senha da sua conta.','O torneio privado precisa de uma senha com pelo menos 6 caracteres.','A senha está incorreta ou ainda não foi configurada.','Torneio privado','Digite a senha para participar. Os convidados também precisam dela.','Salvar senha','Senha salva. Os jogadores inscritos mantêm o acesso.','Configurar senha','Este torneio foi criado antes desta opção. Configure uma senha para permitir novas inscrições.','Compartilhe o link e a senha separadamente com seus convidados.','Torneios públicos','Encontre uma copa e participe enquanto as inscrições estiverem abertas.','Nenhum torneio público neste estado. Você pode criar um.','Vagas','Início manual pelo organizador','Ver classificação','Página','Anterior','Próxima','Inscrições abertas','Em jogo','Finalizados'],
'en':['Public','Private','Visibility','Tournament password','Public: listed in Tournaments. Private: by link or invitation, with a password.','Use 6–128 characters. Share with your invitees; do not use your account password.','Private tournaments need a password with at least 6 characters.','The password is incorrect or has not been configured yet.','Private tournament','Enter the password to join. Invited friends need it too.','Save password','Password saved. Enrolled players keep their access.','Set password','This tournament predates this option. Set a password to allow new registrations.','Share the link and password separately with your invitees.','Public tournaments','Find a cup and join while registration is open.','No public tournaments with this status. You can create one.','Places','Started manually by the host','View standings','Page','Previous','Next','Registration open','Playing','Finished'],
}.items():
 TEXTS[language].update(zip(['public','private','visibility','password','visibility_help','password_help','password_required','wrong_password','locked','locked_help','password_save','password_saved','password_setup','legacy_password_help','private_share_help','discover','discover_help','public_empty','places','manual_start','view_standings','page','previous','next','filter_lobby','filter_active','filter_finished'],values))
for language,intro in {'es':'Encontrá un torneo público o creá una copa privada para tus amigos.','pt':'Encontre um torneio público ou crie uma copa privada para seus amigos.','en':'Find a public tournament or create a private cup for friends.'}.items():
 TEXTS[language]['intro']=intro

for language,text in {'es':'Elegí la visibilidad, los cupos y el tiempo. El organizador inicia cuando los jugadores estén listos.','pt':'Escolha a visibilidade, as vagas e o tempo. O organizador inicia quando os jogadores estiverem prontos.','en':'Choose visibility, capacity and time. The host starts when players are ready.'}.items():
 TEXTS[language]['create_help']=text
