from django.urls import path
from .views import home, games_list, game_detail, game_create,save_move
from . import shop, matchmaking, blindfold, views, social, learning, workspace, tournaments, daily_training, weekly, review_practice, notices


urlpatterns = [
    path('shop/', shop.shop, name='shop'),
    path('shop/equip/', shop.equip, name='shop_equip'),
    path('invitations/<int:invitation_id>/search/', matchmaking.search_tick, name='search_tick'),
    path('blindfold/', blindfold.landing, name='blindfold'),
    path('blindfold/position/', blindfold.position, name='blindfold_position'),
    path('notifications/dismiss/<str:key>/', notices.dismiss, name='notice_dismiss'),
    path("learning/reviews/<int:review_id>/practice/",review_practice.play,name="review_practice"),
    path("learning/reviews/<int:review_id>/practice/start/",review_practice.start,name="review_practice_start"),
    path("learning/practice/answer/",review_practice.answer,name="review_practice_answer"),
    path('training/weekly/', weekly.weekly_challenge, name='weekly_challenge'),
    path('training/weekly/start/', weekly.weekly_start, name='weekly_start'),
    path('training/weekly/play/<int:entry_id>/', weekly.weekly_play, name='weekly_play'),
    path('training/weekly/answer/', weekly.weekly_answer, name='weekly_answer'),
    path('training/today/', daily_training.daily_training, name='daily_training'),
    path('training/today/start/', daily_training.daily_training_start, name='daily_training_start'),
    path('training/today/answer/', daily_training.daily_training_answer, name='daily_training_answer'),
    path('tournament-notices/<int:notice_id>/read/', tournaments.tournament_notice_read, name='tournament_notice_read'),
    path('tournaments/', tournaments.tournament_list, name='tournaments'),
    path('tournaments/new/', tournaments.tournament_create, name='tournament_create'),
    path('tournaments/<uuid:token>/', tournaments.tournament_detail, name='tournament_detail'),
    path('tournaments/<uuid:token>/action/', tournaments.tournament_action, name='tournament_action'),
    path('tournaments/<uuid:token>/state/', tournaments.tournament_state, name='tournament_state'),
    path('games/active/', workspace.active_games, name='active_games'),
    path('learning/', learning.learning_history, name='learning'),
    path('learning/reviews/<int:review_id>/', learning.review_detail, name='review_detail'),
    path('learning/reviews/<int:review_id>/goal/', learning.review_goal, name='review_goal'),
    path('games/<int:game_id>/review/', learning.game_review, name='game_review'),
    path('games/<int:game_id>/rematch/', learning.rematch, name='game_rematch'),
    path('rematches/<int:invitation_id>/accept/', learning.rematch_accept, name='rematch_accept'),
    path('friends/', social.friends, name='friends'),
    path('friends/<int:user_id>/action/', social.friend_action, name='friend_action'),
    path('friends/<int:user_id>/challenge/', social.friend_challenge, name='friend_challenge'),
    path('', home, name='home'),
    path('language/', views.set_language, name='set_language'),
    path('training/', views.training, name='training'),
    path('practice/', views.practice, name='practice'),
    path('practice/move/', views.practice_move, name='practice_move'),
    path('practice/legal-moves/', views.practice_legal_moves, name='practice_legal_moves'),
    path('blitz/', views.blitz, name='blitz'),
    path('blitz/save/', views.blitz_save, name='blitz_save'),
    path('streak/', views.streak, name='streak'),
    path('streak/save/', views.streak_save, name='streak_save'),
    path('daily/', views.daily_puzzle, name='daily_puzzle'),
    path('daily/start/', views.daily_start, name='daily_start'),
    path('daily/move/', views.daily_move, name='daily_move'),
    path('profile/stats/', views.profile_stats, name='profile_stats'),
    path('profile/achievements/', views.profile_achievements, name='profile_achievements'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('games/', games_list, name='games_list'),
    path('games/new/', game_create, name='game_create'),
    path('invitations/<int:invitation_id>/waiting/', views.game_invitation_wait, name='game_invitation_wait'),
    path('invitations/<int:invitation_id>/status/', views.invitation_status, name='invitation_status'),
    path('invitations/<int:invitation_id>/cancel/', views.cancel_invitation, name='cancel_invitation'),
    path('invitations/link/<uuid:token>/join/', views.accept_invitation_link, name='accept_invitation_link'),
    path('invitations/<int:invitation_id>/accept/', views.accept_invitation, name='accept_invitation'),
    path('invitations/<int:invitation_id>/reject/', views.reject_invitation, name='reject_invitation'),
    path('notifications/games/', views.game_notifications, name='game_notifications'),
    path('analyze/', views.game_analyzer, name='game_analyzer'),
    path('games/<int:game_id>/save-move/', views.save_move, name='save_move'),
    path('games/<int:game_id>/mark-finished/', views.mark_finished, name='mark_finished'),
    path('games/<int:game_id>/offer-draw/', views.offer_draw, name='offer_draw'),
    path('games/<int:game_id>/answer-draw/', views.answer_draw_offer, name='answer_draw_offer'),
    path('games/<int:game_id>/resign/', views.resign_game, name='resign_game'),
    path('games/<int:game_id>/moves/', views.game_moves, name='game_moves'),
    path('games/<int:game_id>/state/', views.game_state, name='game_state'),
    path('games/<int:game_id>/chat/', views.game_chat, name='game_chat'),
    path('games/<int:game_id>/', game_detail, name='game_detail'),
    path('idioma/', views.set_language),
    path('practica/', views.practice),
    path('puzzles/', views.practice),
    path('practica/mover/', views.practice_move),
    path('practica/movimientos-legales/', views.practice_legal_moves),
    path('partidas/', games_list),
    path('partidas/nova/', game_create),
    path('partidas/<int:game_id>/', game_detail),
    path('convites/<int:invitation_id>/aguardando/', views.game_invitation_wait),
    path('convites/<int:invitation_id>/status/', views.invitation_status),
    path('convites/<int:invitation_id>/cancelar/', views.cancel_invitation),
    path('convites/link/<uuid:token>/entrar/', views.accept_invitation_link),
    path('convites/<int:invitation_id>/aceitar/', views.accept_invitation),
    path('convites/<int:invitation_id>/recusar/', views.reject_invitation),
    path('notificacoes/partidas/', views.game_notifications),
    path('analisar/', views.game_analyzer),
    path('engine-move/', views.engine_move, name='engine_move'),
    path('coach-analysis/', views.coach_analysis, name='coach_analysis'),
    path('trainer-chat/', views.trainer_chat, name='trainer_chat'),
]
