KEYS=['title','intro','rules','start','continue','practice','ranking','points','attempts','not_started','empty_friends','history','history_empty','week','ends','closed','open','result','back','friends','hint','reveal','correct','wrong','practice_correct','practice_wrong','hint_feedback','shown','finish','summary','independent','helped','origin','goal','deadline','view_result','previous','next','page','completed','scored_positions']
ROWS={
'es':['Desafío semanal entre amigos','Cinco posiciones de mate, las mismas para todos. Competí por precisión y después practicá todo lo que quieras.','Cada posición da 10 puntos si encontrás el mate en tu primer intento. Una jugada legal incorrecta, una pista o ver la solución deja esa posición en 0 puntos. Reintentar sirve para aprender y no modifica el puntaje. No hay reloj ni desempate por velocidad: con los mismos puntos comparten posición. No cambia tu Elo, XP ni rating de puzzles.','Participar esta semana','Continuar desafío','Practicar sin cambiar puntos','Clasificación entre amigos','Puntos','Intentos puntuados','Sin participar','Agregá amigos para comparar resultados. Mientras tanto, podés participar y guardar tu resultado.','Mis resultados anteriores','Tus resultados semanales aparecerán acá.','Semana','Cierra','Semana finalizada · resultado definitivo','Semana en juego','Tu resultado','Volver al desafío semanal','Ver mis amigos','Pedir pista · 0 puntos','Ver solución · 0 puntos','¡Mate! Sumaste 10 puntos con tu primer intento.','No es mate. Tu intento puntuado quedó en 0 puntos; ahora podés practicar sin límite.','¡Bien! Encontraste el mate practicando. Los puntos se mantienen.','Todavía no es mate. Probá otra jugada: estás practicando sin cambiar puntos.','Esta posición queda sin puntos. Mirá las jugadas de esta pieza: {piece}.','Solución vista. Esta posición no suma puntos.','Práctica completada','Practicaste {total} posiciones. Tu clasificación usa solamente los primeros intentos puntuados.','Mates encontrados al primer intento','Posiciones practicadas sin puntos','Desafío compartido de la semana','Encontrá un mate en una jugada.','La semana termina el lunes a las 00:00 UTC. El cierre se muestra en tu horario local.','Ver resultado y practicar','Anterior','Siguiente','Página','Intentos puntuados completados','Posiciones con intento puntuado'],
'pt':['Desafio semanal entre amigos','Cinco posições de mate, iguais para todos. Compita por precisão e depois pratique à vontade.','Cada posição vale 10 pontos se você encontrar o mate na primeira tentativa. Uma jogada legal incorreta, uma dica ou ver a solução deixa a posição com 0 pontos. Repetir ajuda a aprender e não muda a pontuação. Sem relógio ou desempate por velocidade: pontuações iguais dividem a posição. Não muda Elo, XP ou rating de puzzles.','Participar esta semana','Continuar desafio','Praticar sem mudar pontos','Classificação entre amigos','Pontos','Tentativas pontuadas','Não participou','Adicione amigos para comparar resultados. Enquanto isso, você pode participar e guardar seu resultado.','Meus resultados anteriores','Seus resultados semanais aparecerão aqui.','Semana','Encerra','Semana encerrada · resultado definitivo','Semana em andamento','Seu resultado','Voltar ao desafio semanal','Ver meus amigos','Pedir dica · 0 pontos','Ver solução · 0 pontos','Xeque-mate! Você ganhou 10 pontos na primeira tentativa.','Não é mate. Sua tentativa pontuada ficou com 0 pontos; agora você pode praticar sem limite.','Muito bem! Encontrou o mate praticando. A pontuação não muda.','Ainda não é mate. Tente outra jogada: você está praticando sem mudar pontos.','Esta posição fica sem pontos. Observe as jogadas desta peça: {piece}.','Solução vista. Esta posição não soma pontos.','Prática concluída','Você praticou {total} posições. A classificação usa apenas as primeiras tentativas pontuadas.','Mates encontrados na primeira tentativa','Posições praticadas sem pontos','Desafio compartilhado da semana','Encontre um mate em uma jogada.','A semana termina na segunda às 00:00 UTC. O encerramento aparece no seu horário local.','Ver resultado e praticar','Anterior','Próxima','Página','Tentativas pontuadas concluídas','Posições com tentativa pontuada'],
'en':['Weekly challenge with friends','Five mate positions, the same for everyone. Compete on accuracy, then practice as much as you like.','Each position earns 10 points if you find mate on your first attempt. An incorrect legal move, a hint or viewing the solution scores 0 for that position. Retries help you learn and do not change points. No clock or speed tiebreak: equal scores share a place. Elo, XP and puzzle rating stay unchanged.','Join this week','Continue challenge','Practice without changing points','Friends standings','Points','Scored attempts','Not participating','Add friends to compare results. You can still participate and save your own result.','My previous results','Your weekly results will appear here.','Week','Closes','Week closed · final result','Week in progress','Your result','Back to weekly challenge','View my friends','Get hint · 0 points','Show solution · 0 points','Checkmate! You earned 10 points on your first attempt.','Not mate. Your scored attempt earned 0 points; you can now practice without limits.','Nice! You found mate while practicing. Points stay unchanged.','Not mate yet. Try another move: you are practicing without changing points.','This position scores no points. Look at moves by this piece: {piece}.','Solution viewed. This position earns no points.','Practice completed','You practiced {total} positions. Standings use only your first scored attempts.','Mates found on the first attempt','Positions practiced without points','Shared challenge for the week','Find checkmate in one move.','The week ends Monday at 00:00 UTC. The closing time is shown in your local time.','View result and practice','Previous','Next','Page','Scored attempts completed','Positions with a scored attempt'],
}
TEXTS={lang:dict(zip(KEYS,row)) for lang,row in ROWS.items()}
def weekly_navigation(request):
 from .i18n import current_language
 return {'weekly':TEXTS[current_language(request)]}

for lang,label in {'es':'Cómo se puntúa','pt':'Como funciona a pontuação','en':'How scoring works'}.items():
 TEXTS[lang]['rules_title']=label

for lang,values in {
 'es':['Solo práctica: el resultado puntuado original se conserva.','Pista para practicar, sin cambiar puntos: mirá las jugadas de esta pieza: {piece}.','Solución vista para practicar. Los puntos registrados se conservan.','Intentos que sumaron 10 puntos','Intentos que quedaron en 0 puntos'],
 'pt':['Somente prática: o resultado pontuado original é preservado.','Dica para praticar sem mudar pontos: observe esta peça: {piece}.','Solução vista para praticar. Os pontos registrados são preservados.','Tentativas que somaram 10 pontos','Tentativas que ficaram com 0 pontos'],
 'en':['Practice only: your original scored result is preserved.','Practice hint, without changing points: look at moves by this piece: {piece}.','Solution viewed for practice. Recorded points are preserved.','Attempts that earned 10 points','Attempts that earned 0 points'],
}.items():
 TEXTS[lang].update(zip(['practice_mode','practice_hint','practice_shown','independent','helped'],values))


for lang, label in [('es','Jugador'),('pt','Jogador'),('en','Player')]:
    TEXTS[lang]['player']=label

for lang, label in [('es','Volver a Entrenar'),('pt','Voltar para Treinar'),('en','Back to Training')]:
    TEXTS[lang]['training_back']=label
