# Generated by Django 6.0.5 on 2026-07-14 22:01

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPuzzleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzles_resueltos', models.PositiveIntegerField(default=0)),
                ('puzzles_correctos', models.PositiveIntegerField(default=0)),
                ('puzzles_incorrectos', models.PositiveIntegerField(default=0)),
                ('porcentaje_de_aciertos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tiempo_total', models.DurationField(default=datetime.timedelta)),
                ('tiempo_promedio', models.DurationField(default=datetime.timedelta)),
                ('mejor_racha', models.PositiveIntegerField(default=0)),
                ('racha_actual', models.PositiveIntegerField(default=0)),
                ('ultimo_puzzle_resuelto', models.CharField(blank=True, max_length=120)),
                ('fecha_ultimo_entrenamiento', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estadistica de puzzles',
                'verbose_name_plural': 'estadisticas de puzzles',
            },
        ),
    ]
