# Generated by Django 6.0.5 on 2026-07-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpuzzlestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpuzzlestats',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userpuzzlestats',
            name='xp_del_nivel_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpuzzlestats',
            name='xp_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
