# Generated by Django 6.0.5 on 2026-07-14 22:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


ACHIEVEMENTS = (
    ('first_puzzle', 'puzzles_correctos', 1, 'Primer puzzle', 'Resuelve tu primer puzzle.', 10),
    ('puzzles_10', 'puzzles_correctos', 10, '10 puzzles', 'Resuelve 10 puzzles.', 20),
    ('puzzles_50', 'puzzles_correctos', 50, '50 puzzles', 'Resuelve 50 puzzles.', 30),
    ('puzzles_100', 'puzzles_correctos', 100, '100 puzzles', 'Resuelve 100 puzzles.', 40),
    ('puzzles_500', 'puzzles_correctos', 500, '500 puzzles', 'Resuelve 500 puzzles.', 50),
    ('puzzles_1000', 'puzzles_correctos', 1000, '1000 puzzles', 'Resuelve 1000 puzzles.', 60),
    ('streak_10', 'mejor_racha', 10, '10 correctos seguidos', 'Consigue una racha de 10 aciertos.', 70),
    ('streak_25', 'mejor_racha', 25, '25 correctos seguidos', 'Consigue una racha de 25 aciertos.', 80),
    ('streak_50', 'mejor_racha', 50, '50 correctos seguidos', 'Consigue una racha de 50 aciertos.', 90),
    ('xp_1000', 'xp_total', 1000, '1000 XP', 'Acumula 1000 XP.', 100),
    ('level_10', 'nivel', 10, 'Nivel 10', 'Alcanza el nivel 10.', 110),
    ('level_25', 'nivel', 25, 'Nivel 25', 'Alcanza el nivel 25.', 120),
    ('level_50', 'nivel', 50, 'Nivel 50', 'Alcanza el nivel 50.', 130),
)


def create_default_achievements(apps, schema_editor):
    Achievement = apps.get_model('accounts', 'Achievement')

    for key, metric, threshold, name, description, sort_order in ACHIEVEMENTS:
        Achievement.objects.update_or_create(
            key=key,
            defaults={
                'name': name,
                'description': description,
                'metric': metric,
                'threshold': threshold,
                'sort_order': sort_order,
            },
        )


def remove_default_achievements(apps, schema_editor):
    Achievement = apps.get_model('accounts', 'Achievement')
    Achievement.objects.filter(key__in=[achievement[0] for achievement in ACHIEVEMENTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpuzzlestats_nivel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=220)),
                ('metric', models.CharField(choices=[('puzzles_correctos', 'Puzzles correctos'), ('mejor_racha', 'Mejor racha'), ('xp_total', 'XP total'), ('nivel', 'Nivel')], max_length=40)),
                ('threshold', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'logro',
                'verbose_name_plural': 'logros',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unlocks', to='accounts.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'logro de usuario',
                'verbose_name_plural': 'logros de usuarios',
                'ordering': ['-unlocked_at', 'achievement__sort_order'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.RunPython(create_default_achievements, remove_default_achievements),
    ]
