# Generated by Django 6.0.5 on 2026-07-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpuzzlestats',
            name='mejor_rating',
            field=models.PositiveIntegerField(default=800),
        ),
        migrations.AddField(
            model_name='userpuzzlestats',
            name='puzzle_rating',
            field=models.PositiveIntegerField(default=800),
        ),
        migrations.AddField(
            model_name='userpuzzlestats',
            name='ultimo_cambio_rating',
            field=models.IntegerField(default=0),
        ),
    ]
