# Generated by Django 6.0.9 on 2026-10-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpuzzlestats_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
