const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('games/static/games/workspace.js','utf8');
const snippet=source.slice(source.indexOf('    function hasUnfinishedCoachGames()'),source.indexOf("    window.addEventListener('focus', refresh)"));
const store=new Map();let handler,actor='user:1',submitted=0;
const key=name=>'gchess-workspace-v1:'+actor+':'+name;
const put=(name,value)=>store.set(key(name),JSON.stringify(value));
const dialog={open:false,listeners:{},showModal(){this.open=true;},close(){this.open=false;},addEventListener(type,fn){this.listeners[type]=fn;}};
const cancel={addEventListener(type,fn){this.click=fn;}};
const confirm={addEventListener(type,fn){this.click=fn;}};
const submit=()=>{let blocked=false;handler({preventDefault:()=>blocked=true});if(!blocked)submitted++;return blocked;};
const form={addEventListener(type,fn){assert.equal(type,'submit');handler=fn;},requestSubmit:submit};
const context={read:(name,fallback)=>{try{return JSON.parse(store.get(key(name)))??fallback;}catch{return fallback;}},validId:id=>typeof id==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(id),document:{querySelectorAll:()=>[form],getElementById:id=>({'coach-exit-dialog':dialog,'coach-exit-cancel':cancel,'coach-exit-confirm':confirm}[id])}};
vm.runInNewContext(snippet,context);
put('bots',[{id:'one'},{id:'two',finished:true}]);put('bot:one',{moves:[{from_square:'e2',to_square:'e4'}]});put('bot:two',{moves:[{}]});
const original=store.get(key('bot:one'));
assert.equal(submit(),true);assert.equal(dialog.open,true);cancel.click();assert.equal(dialog.open,false);assert.equal(submitted,0,'cancel keeps the user logged in');assert.equal(store.get(key('bot:one')),original,'warning never clears moves');
submit();confirm.click();assert.equal(submitted,1,'confirm submits the normal logout form once');assert.equal(dialog.open,false);confirm.click();assert.equal(submitted,1,'repeat confirmation is harmless');
submit();dialog.listeners.cancel();dialog.close();confirm.click();assert.equal(submitted,1,'Escape cancels submission');
actor='user:2';assert.equal(submit(),false,'another account never sees the first account’s games');
actor='user:1';put('bots',[{id:'two',finished:true}]);assert.equal(submit(),false,'finished games do not trigger a warning');
put('bots',[{id:'empty'}]);put('bot:empty',{moves:[]});assert.equal(submit(),false,'opening an empty board is not a game in progress');
store.set(key('bot:empty'),'invalid json');assert.equal(submit(),false);
put('bots',{invalid:true});assert.equal(submit(),false);
console.log('Coach logout: cancel, confirm, Escape, account isolation, finished games and invalid storage verified.');
