# Generated by Django 6.0.5 on 2026-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_chessgame_result_chessgame_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='category',
            field=models.CharField(choices=[('casual', 'Casual'), ('ranked', 'Ranqueada'), ('training', 'Treino')], default='casual', max_length=20),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
