# Generated by Django 6.0.5 on 2026-05-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_chessgame_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.PositiveIntegerField()),
                ('from_square', models.CharField(max_length=2)),
                ('to_square', models.CharField(max_length=2)),
                ('piece_type', models.CharField(max_length=20)),
                ('piece_color', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.chessgame')),
            ],
        ),
    ]
