# Generated by Django 6.0.5 on 2026-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='promotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
