# Generated by Django 6.0.5 on 2026-05-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_chessgame_black_user_chessgame_white_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='rating_applied',
            field=models.BooleanField(default=False),
        ),
    ]
