# Generated by Django 6.0.5 on 2026-05-24 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_game_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='black_guest_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='white_guest_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='gamechatmessage',
            name='sender_guest_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='gamechatmessage',
            name='sender_guest_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='creator_guest_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='creator_guest_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamechatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_game_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameinvitation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_game_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
