# Generated by Django 6.0.5 on 2026-07-14 23:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_dailyvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('puzzle_id', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'puzzle diario',
                'verbose_name_plural': 'puzzles diarios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyPuzzleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('resultado', models.CharField(choices=[('in_progress', 'En progreso'), ('correct', 'Correcto'), ('incorrect', 'Incorrecto')], default='in_progress', max_length=20)),
                ('tiempo', models.DurationField(default=datetime.timedelta)),
                ('played_line', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('daily_puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.dailypuzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_puzzle_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intento de puzzle diario',
                'verbose_name_plural': 'intentos de puzzle diario',
                'ordering': ['-date', '-started_at'],
                'unique_together': {('date', 'user')},
            },
        ),
    ]
