# Generated by Django 6.0.5 on 2026-07-17 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_dailypuzzle_dailypuzzleattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlitzBestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('puzzles_resueltos', models.PositiveIntegerField(default=0)),
                ('puzzles_correctos', models.PositiveIntegerField(default=0)),
                ('puzzles_incorrectos', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=180)),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blitz_best_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mejor resultado blitz',
                'verbose_name_plural': 'mejores resultados blitz',
                'ordering': ['-score', '-puzzles_correctos', 'achieved_at'],
            },
        ),
    ]
