# Generated by Django 6.0.5 on 2026-07-17 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_blitzbestresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakBestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mejor_racha', models.PositiveIntegerField(default=0)),
                ('puzzles_resueltos', models.PositiveIntegerField(default=0)),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_best_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mejor racha streak',
                'verbose_name_plural': 'mejores rachas streak',
                'ordering': ['-mejor_racha', '-puzzles_resueltos', 'achieved_at'],
            },
        ),
    ]
