# Generated by Django 6.0.5 on 2026-07-17 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_streakbestresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['owner', '-created_at'], name='game_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['white_user', '-created_at'], name='game_white_user_idx'),
        ),
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['black_user', '-created_at'], name='game_black_user_idx'),
        ),
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['white_guest_id', '-created_at'], name='game_white_guest_idx'),
        ),
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['black_guest_id', '-created_at'], name='game_black_guest_idx'),
        ),
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['status', '-created_at'], name='game_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='gamechatmessage',
            index=models.Index(fields=['game', 'created_at', 'id'], name='chat_game_order_idx'),
        ),
        migrations.AddIndex(
            model_name='gamechatmessage',
            index=models.Index(fields=['game', 'sender', 'id'], name='chat_game_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='gamechatmessage',
            index=models.Index(fields=['game', 'sender_guest_id', 'id'], name='chat_game_guest_idx'),
        ),
        migrations.AddIndex(
            model_name='gameinvitation',
            index=models.Index(fields=['status', 'opponent', 'created_at'], name='invite_status_opp_idx'),
        ),
        migrations.AddIndex(
            model_name='gameinvitation',
            index=models.Index(fields=['status', 'opponent_mode', 'created_at'], name='invite_status_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='gameinvitation',
            index=models.Index(fields=['creator', 'status'], name='invite_creator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='gameinvitation',
            index=models.Index(fields=['token', 'opponent_mode'], name='invite_token_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['game', 'move_number', 'id'], name='move_game_order_idx'),
        ),
    ]
