# Generated by Django 6.0.5 on 2026-10-06 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_friendship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='rematch_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematch_invitations', to='games.chessgame'),
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=2)),
                ('player_color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('goal_completed_at', models.DateTimeField(blank=True, null=True)),
                ('pgn', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.chessgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='review_user_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'fingerprint', 'language', 'player_color'), name='review_unique_user_position')],
            },
        ),
    ]
