# Generated by Django 6.0.5 on 2026-10-07 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_gameinvitation_rematch_of_gamereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='lobby', max_length=12)),
                ('max_players', models.PositiveSmallIntegerField(default=8)),
                ('time_control_minutes', models.PositiveSmallIntegerField(default=10)),
                ('current_round', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='games.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('board_number', models.PositiveSmallIntegerField()),
                ('black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='black_tournament_matches', to=settings.AUTH_USER_MODEL)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournament_match', to='games.chessgame')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='games.tournament')),
                ('white', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='white_tournament_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['round_number', 'board_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('max_players__gte', 2), ('max_players__lte', 16)), name='tournament_capacity_range'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('time_control_minutes__in', [3, 5, 10, 15, 30])), name='tournament_valid_time'),
        ),
        migrations.AddConstraint(
            model_name='tournamententry',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='unique_tournament_player'),
        ),
        migrations.AddConstraint(
            model_name='tournamentmatch',
            constraint=models.UniqueConstraint(fields=('tournament', 'round_number', 'board_number'), name='unique_tournament_board'),
        ),
        migrations.AddConstraint(
            model_name='tournamentmatch',
            constraint=models.CheckConstraint(condition=models.Q(('white', models.F('black')), _negated=True), name='tournament_distinct_players'),
        ),
    ]
