# Generated by Django 6.0.5 on 2026-10-07 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_tournament_tournamententry_tournamentmatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invite', 'Invite'), ('round', 'Round')], max_length=12)),
                ('round_number', models.PositiveSmallIntegerField(default=0)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='games.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'read'], name='tournament_notice_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'user', 'kind', 'round_number'), name='unique_tournament_notice')],
            },
        ),
    ]
