# Generated by Django 6.0.5 on 2026-10-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_dailytraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='password_hash',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='tournament',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='private', max_length=7),
        ),
    ]
