# Generated by Django 6.0.9 on 2026-10-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_playeractivityday'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='blindfold_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='blindfold_only',
            field=models.BooleanField(default=False),
        ),
    ]
