# Generated by Django 6.0.9 on 2026-10-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_cosmeticloadout'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticloadout',
            name='clothing',
            field=models.CharField(choices=[('club', 'Club'), ('ivory', 'Ivory'), ('forest', 'Forest'), ('terracotta', 'Terracotta')], default='club', max_length=20),
        ),
        migrations.AddField(
            model_name='cosmeticloadout',
            name='face',
            field=models.CharField(choices=[('none', 'None'), ('moustache', 'Moustache'), ('glasses', 'Glasses')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='cosmeticloadout',
            name='pieces',
            field=models.CharField(choices=[('rustic', 'Rustic'), ('club', 'Club'), ('modern', 'Modern'), ('tournament', 'Tournament')], default='rustic', max_length=20),
        ),
        migrations.AlterField(
            model_name='cosmeticloadout',
            name='accessory',
            field=models.CharField(choices=[('none', 'None'), ('cap', 'Cap'), ('beret', 'Beret'), ('beanie', 'Beanie'), ('visor', 'Visor')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='cosmeticloadout',
            name='avatar',
            field=models.CharField(choices=[('explorer', 'Explorer'), ('strategist', 'Strategist'), ('mentor', 'Mentor'), ('competitor', 'Competitor')], default='explorer', max_length=20),
        ),
        migrations.AlterField(
            model_name='cosmeticloadout',
            name='board',
            field=models.CharField(choices=[('rustic', 'Rustic'), ('walnut', 'Walnut'), ('slate', 'Slate'), ('sand', 'Sand'), ('ocean', 'Ocean'), ('wine', 'Wine')], default='rustic', max_length=20),
        ),
    ]
