# Generated by Django 6.0.9 on 2026-10-08 00:35

from django.db import migrations, models


def move_legacy_glasses(apps, schema_editor):
    Loadout=apps.get_model('games','CosmeticLoadout')
    Loadout.objects.filter(face='glasses').update(eyewear='glasses',face='none')

def restore_legacy_glasses(apps, schema_editor):
    Loadout=apps.get_model('games','CosmeticLoadout')
    Loadout.objects.filter(face='none',eyewear='glasses').update(face='glasses')

class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_cosmeticloadout_clothing_cosmeticloadout_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticloadout',
            name='earrings',
            field=models.CharField(choices=[('none', 'None'), ('gold_hoops', 'Gold_Hoops'), ('silver_hoops', 'Silver_Hoops'), ('studs', 'Studs'), ('diamond', 'Diamond'), ('chain', 'Chain'), ('black_plugs', 'Black_Plugs')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='cosmeticloadout',
            name='eyewear',
            field=models.CharField(choices=[('none', 'None'), ('glasses', 'Glasses'), ('round', 'Round'), ('aviator', 'Aviator'), ('square', 'Square'), ('sunglasses', 'Sunglasses'), ('sport', 'Sport'), ('monocle', 'Monocle'), ('visor_lens', 'Visor_Lens')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='cosmeticloadout',
            name='hairstyle',
            field=models.CharField(choices=[('none', 'None'), ('dreads', 'Dreads'), ('mohawk', 'Mohawk'), ('afro', 'Afro'), ('braids', 'Braids'), ('bun', 'Bun'), ('ponytail', 'Ponytail'), ('spikes', 'Spikes'), ('waves', 'Waves'), ('curls', 'Curls'), ('sidepart', 'Sidepart'), ('silver_crop', 'Silver_Crop'), ('blue_mohawk', 'Blue_Mohawk'), ('pink_bob', 'Pink_Bob'), ('green_spikes', 'Green_Spikes'), ('red_braids', 'Red_Braids'), ('blond_quiff', 'Blond_Quiff'), ('purple_dreads', 'Purple_Dreads'), ('punk', 'Punk'), ('shaved', 'Shaved')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='cosmeticloadout',
            name='accessory',
            field=models.CharField(choices=[('none', 'None'), ('cap', 'Cap'), ('beret', 'Beret'), ('beanie', 'Beanie'), ('visor', 'Visor'), ('fedora', 'Fedora'), ('cowboy', 'Cowboy'), ('bucket', 'Bucket'), ('top_hat', 'Top_Hat'), ('crown', 'Crown'), ('pirate', 'Pirate'), ('straw', 'Straw'), ('turban', 'Turban'), ('wizard', 'Wizard'), ('helmet', 'Helmet'), ('sailor', 'Sailor'), ('flat_cap', 'Flat_Cap'), ('earflap', 'Earflap'), ('laurel', 'Laurel'), ('chef', 'Chef')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='cosmeticloadout',
            name='avatar',
            field=models.CharField(choices=[('explorer', 'Explorer'), ('strategist', 'Strategist'), ('mentor', 'Mentor'), ('competitor', 'Competitor'), ('curly', 'Curly'), ('scout', 'Scout'), ('captain', 'Captain'), ('pilot', 'Pilot'), ('dinosaur', 'Dinosaur'), ('alien', 'Alien'), ('bear', 'Bear'), ('tiger', 'Tiger'), ('robot', 'Robot'), ('crocodile', 'Crocodile'), ('shark', 'Shark'), ('fox', 'Fox'), ('wolf', 'Wolf'), ('panda', 'Panda'), ('astronaut', 'Astronaut'), ('dragon', 'Dragon')], default='explorer', max_length=20),
        ),
        migrations.AlterField(
            model_name='cosmeticloadout',
            name='board',
            field=models.CharField(choices=[('rustic', 'Rustic'), ('walnut', 'Walnut'), ('slate', 'Slate'), ('sand', 'Sand'), ('ocean', 'Ocean'), ('wine', 'Wine'), ('gold', 'Gold'), ('lava', 'Lava'), ('emerald', 'Emerald'), ('midnight', 'Midnight'), ('ice', 'Ice'), ('copper', 'Copper'), ('amethyst', 'Amethyst'), ('rose', 'Rose'), ('olive', 'Olive'), ('marble', 'Marble'), ('coffee', 'Coffee'), ('royal', 'Royal'), ('silver', 'Silver'), ('obsidian', 'Obsidian')], default='rustic', max_length=20),
        ),
        migrations.AlterField(
            model_name='cosmeticloadout',
            name='clothing',
            field=models.CharField(choices=[('club', 'Club'), ('ivory', 'Ivory'), ('forest', 'Forest'), ('terracotta', 'Terracotta'), ('hoodie', 'Hoodie'), ('denim', 'Denim'), ('leather', 'Leather'), ('tuxedo', 'Tuxedo'), ('jersey', 'Jersey'), ('sweater', 'Sweater'), ('bomber', 'Bomber'), ('varsity', 'Varsity'), ('kimono', 'Kimono'), ('armor', 'Armor'), ('cape', 'Cape'), ('space_suit', 'Space_Suit'), ('striped', 'Striped'), ('hawaiian', 'Hawaiian'), ('vest', 'Vest'), ('puffer', 'Puffer')], default='club', max_length=20),
        ),
        migrations.AlterField(
            model_name='cosmeticloadout',
            name='face',
            field=models.CharField(choices=[('none', 'None'), ('moustache', 'Moustache'), ('stubble', 'Stubble'), ('goatee', 'Goatee'), ('full_beard', 'Full_Beard'), ('long_beard', 'Long_Beard'), ('handlebar', 'Handlebar'), ('braided_beard', 'Braided_Beard'), ('silver_beard', 'Silver_Beard')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='cosmeticloadout',
            name='pieces',
            field=models.CharField(choices=[('rustic', 'Rustic'), ('club', 'Club'), ('modern', 'Modern'), ('tournament', 'Tournament'), ('gold', 'Gold'), ('silver', 'Silver'), ('copper', 'Copper'), ('obsidian', 'Obsidian'), ('ivory', 'Ivory'), ('jade', 'Jade'), ('ruby', 'Ruby'), ('sapphire', 'Sapphire'), ('amethyst', 'Amethyst'), ('lava', 'Lava'), ('ice', 'Ice'), ('rose', 'Rose'), ('bronze', 'Bronze'), ('pearl', 'Pearl'), ('midnight', 'Midnight'), ('sandstone', 'Sandstone')], default='rustic', max_length=20),
        ),
        migrations.RunPython(move_legacy_glasses,restore_legacy_glasses),
    ]
