# Generated by Django 6.0.9 on 2026-10-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_cosmeticloadout_earrings_cosmeticloadout_eyewear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticloadout',
            name='avatar',
            field=models.CharField(choices=[('explorer', 'Explorer'), ('strategist', 'Strategist'), ('mentor', 'Mentor'), ('competitor', 'Competitor'), ('curly', 'Curly'), ('scout', 'Scout'), ('captain', 'Captain'), ('pilot', 'Pilot'), ('dinosaur', 'Dinosaur'), ('alien', 'Alien'), ('bear', 'Bear'), ('tiger', 'Tiger'), ('robot', 'Robot'), ('crocodile', 'Crocodile'), ('shark', 'Shark'), ('fox', 'Fox'), ('wolf', 'Wolf'), ('panda', 'Panda'), ('astronaut', 'Astronaut'), ('dragon', 'Dragon'), ('elephant', 'Elephant'), ('lion', 'Lion'), ('croc_safari', 'Croc_Safari'), ('duck', 'Duck'), ('giraffe', 'Giraffe'), ('dog', 'Dog'), ('messi', 'Messi'), ('cat', 'Cat'), ('gorilla', 'Gorilla'), ('rabbit', 'Rabbit'), ('raccoon', 'Raccoon'), ('penguin', 'Penguin'), ('owl', 'Owl'), ('hippo', 'Hippo'), ('rhino', 'Rhino'), ('zebra', 'Zebra'), ('horse', 'Horse'), ('octopus', 'Octopus'), ('eagle', 'Eagle'), ('skeleton', 'Skeleton')], default='explorer', max_length=20),
        ),
    ]
