# Generated by Django 6.0.9 on 2026-10-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_dailycheckin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticloadout',
            name='avatar',
            field=models.CharField(choices=[('explorer', 'Explorer'), ('piece_pawn', 'Piece_Pawn'), ('strategist', 'Strategist'), ('pilot', 'Pilot'), ('mentor', 'Mentor'), ('competitor', 'Competitor'), ('curly', 'Curly'), ('scout', 'Scout'), ('captain', 'Captain'), ('dinosaur', 'Dinosaur'), ('alien', 'Alien'), ('bear', 'Bear'), ('tiger', 'Tiger'), ('piece_bishop', 'Piece_Bishop'), ('robot', 'Robot'), ('crocodile', 'Crocodile'), ('shark', 'Shark'), ('fox', 'Fox'), ('wolf', 'Wolf'), ('panda', 'Panda'), ('astronaut', 'Astronaut'), ('dragon', 'Dragon'), ('elephant', 'Elephant'), ('piece_knight', 'Piece_Knight'), ('lion', 'Lion'), ('croc_safari', 'Croc_Safari'), ('duck', 'Duck'), ('giraffe', 'Giraffe'), ('dog', 'Dog'), ('messi', 'Messi'), ('cat', 'Cat'), ('piece_rook', 'Piece_Rook'), ('gorilla', 'Gorilla'), ('rabbit', 'Rabbit'), ('raccoon', 'Raccoon'), ('penguin', 'Penguin'), ('owl', 'Owl'), ('hippo', 'Hippo'), ('rhino', 'Rhino'), ('zebra', 'Zebra'), ('horse', 'Horse'), ('octopus', 'Octopus'), ('eagle', 'Eagle'), ('skeleton', 'Skeleton'), ('bull', 'Bull'), ('raven', 'Raven'), ('piece_king', 'Piece_King'), ('piece_queen', 'Piece_Queen')], default='explorer', max_length=20),
        ),
    ]
